[env:creality422]
platform = ststm32
board = genericSTM32F103RE
framework = arduino
board_build.offset = 0x7000
board_upload.offset_address = 0x08007000
build_flags =
  -DSERIAL_TX_BUFFER_SIZE=256
  -DSERIAL_RX_BUFFER_SIZE=64
  -DHAL_UART_MODULE_ENABLED
monitor_speed = 115200
upload_protocol = stlink
